[book]
title = "Analytical Interview Prep Guide"
authors = ["Moshe Shamouilian"]
src = "src"


[output.html]
git-repository-url = "https://github.com/moshesham/Analytical-Interview-Prep-Guide"
edit-url-template = "https://github.com/moshesham/Analytical-Interview-Prep-Guide/edit/main/{path}"
